services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    entrypoint: ['bash', '/compose/mongo_setup.sh']
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db:z
      - ./compose:/compose/:z
    restart: always
    command: --quiet
    healthcheck:
      test: mongosh --quiet --eval "try { var status = rs.status(); if (status.members[0].stateStr === 'PRIMARY') { quit(0); } else { quit(1); } } catch(e) { quit(1); }"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh:z
    healthcheck:
      test: ['CMD', 'stat', '/tmp/READY']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - cdp-tenant

  cdp-defra-id-stub:
    image: defradigital/cdp-defra-id-stub:latest
    ports:
      - '3200:3200'
      - '3000:3000'
      - '7337:7337'
    depends_on:
      redis:
        condition: service_started
    environment:
      PORT: 3200
      NODE_ENV: development
      REDIS_HOST: redis
      SESSION_CACHE_ENGINE: redis
      USE_SINGLE_INSTANCE_CACHE: true
      APP_BASE_URL: http://localhost:3200
    networks:
      - cdp-tenant

  cdp-uploader:
    image: defradigital/cdp-uploader:latest
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      VIRTUAL_HOST: ~^uploader\..*\.sslip\.io
      VIRTUAL_PATH: /
      VIRTUAL_PORT: 7337
      PORT: 7337
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      MOCK_VIRUS_SCAN_ENABLED: true
      MOCK_VIRUS_RESULT_DELAY: 3
      SQS_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
    network_mode: 'service:cdp-defra-id-stub'

  waste-movement-backend:
    image: defradigital/waste-movement-backend:latest
    ports:
      - '3002:3002'
    depends_on:
      mongodb:
        condition: service_healthy
      waste-tracking-id-backend:
        condition: service_started
    environment:
      PORT: 3002
      NODE_ENV: development
      ENVIRONMENT: local
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      ORG_API_CODES: 'MGUyMWM0NzctODg1My00NTg5LTk5MGMtYWE3ODJiNzQzMWVlPTBlMjFjNDc3LTg4NTMtNDU4OS05OTBjLWFhNzgyYjc0MzFlZQ=='
      MONGO_READ_PREFERENCE: primary
      ACCESS_CRED_WASTE_MOVEMENT_BACKEND: d2FzdGUtbW92ZW1lbnQtYmFja2VuZD05MmZhNjgxZS00NGI0LTRiOWMtOGY3YS01OWMxMTc3NTc0NTI=
      ACCESS_CRED_WASTE_MOVEMENT_EXTERNAL_API: d2FzdGUtbW92ZW1lbnQtZXh0ZXJuYWwtYXBpPTkyZmE2ODFlLTQ0YjQtNGI5Yy04ZjdhLTU5YzExNzc1NzQ1Mg==
      ACCESS_CRED_WASTE_ORGANISATIONS_BACKEND: d2FzdGUtb3JnYW5pc2F0aW9ucy1iYWNrZW5kPTkyZmE2ODFlLTQ0YjQtNGI5Yy04ZjdhLTU5YzExNzc1NzQ1Mg==
      SERVICE_AUTH_PASSWORD: 92fa681e-44b4-4b9c-8f7a-59c117757452
      SERVICE_AUTH_PASSWORD_WASTE_MOVEMENT_BACKEND: 92fa681e-44b4-4b9c-8f7a-59c117757452
      WASTE_TRACKING_SERVICE_URL: http://waste-tracking-id-backend:3001
    networks:
      - cdp-tenant

  waste-tracking-id-backend:
    image: defradigital/waste-tracking-id-backend:latest
    ports:
      - '3003:3001'
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      PORT: 3001
      NODE_ENV: development
      ENVIRONMENT: local
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      ACCESS_CRED_WASTE_MOVEMENT_EXTERNAL_API: d2FzdGUtbW92ZW1lbnQtZXh0ZXJuYWwtYXBpPTkyZmE2ODFlLTQ0YjQtNGI5Yy04ZjdhLTU5YzExNzc1NzQ1Mg==
      ACCESS_CRED_WASTE_MOVEMENT_BACKEND: d2FzdGUtbW92ZW1lbnQtYmFja2VuZD05MmZhNjgxZS00NGI0LTRiOWMtOGY3YS01OWMxMTc3NTc0NTI=
    networks:
      - cdp-tenant

  waste-organisation-backend:
    image: defradigital/waste-organisation-backend:latest
    ports:
      - '3001:3001'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
      - '.env'
    environment:
      PORT: 3001
      NODE_ENV: development
      S3_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      AWS_S3_FORCE_PATH_STYLE: true
      SPREADSHEET_SQS_QUEUE: waste-receiver-background-process
      BULK_UPLOAD_ENDPOINT: 'http://waste-movement-backend:3002'
      BULK_UPLOAD_USERNAME: 'waste-organisations-backend'
      BULK_UPLOAD_PASSWORD: '92fa681e-44b4-4b9c-8f7a-59c117757452'
      WASTE_CLIENT_AUTH_TEST: test
      AWS_S3_CHECKSUM_MODE: DISABLED
      GOV_NOTIFY_KEY: ${GOV_NOTIFY_KEY}
      LOG_LEVEL: trace
    networks:
      - cdp-tenant

  waste-organisation-frontend:
    build:
      context: .
      target: development
    volumes:
      - ./package.json:/home/node/package.json:z
      - ./package-lock.json:/home/node/package-lock.json:z
      - ./src:/home/node/src:z
      - ./webpack.config.js:/home/node/webpack.config.js:z
      - ./postcss.config.js:/home/node/postcss.config.js:z
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
      cdp-defra-id-stub:
        condition: service_started
      waste-organisation-backend:
        condition: service_started
      cdp-uploader:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      SESSION_CACHE_ENGINE: redis
      AUTH_DEFRA_ID_OIDC_CONFIGURATION_URL: 'http://localhost:3200/cdp-defra-id-stub/.well-known/openid-configuration'
      BACKEND_API: http://waste-organisation-backend:3001
      FILE_UPLOAD_SERVICE_URL: http://localhost:7337
      BACKEND_API_PRESHARED_KEY: test
      GOVPAY_API_KEY: ${GOVPAY_API_KEY}
      GOVPAY_API_URL: ${GOVPAY_API_URL:-https://publicapi.payments.service.gov.uk/v1}
      FEATURE_FLAG_UPDATE_SPREADSHEET: true
      FEATURE_FLAG_ACCOUNT_PAGE: true
      FEATURE_FLAG_SERVICE_CHARGE: true
      FEATURE_FLAG_SEARCH_PAGE: true
      FEATURE_FLAG_TEST_ERRORS: true
      FEATURE_FLAG_NEW_ACCOUNT_PAGE: true
    network_mode: 'service:cdp-defra-id-stub'

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
