services:
  ngrok:
    image: ngrok/ngrok:latest
    env_file:
      - '.env'
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: 
    - 'http' 
    - '--url=${NGROK_URL}' 
    - '3000'
    network_mode: host 
